name: grocery_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_thermal_printer: ^1.2.1+1
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: Sevillana
      fonts:
        - asset: assets/fonts/Sevillana/Sevillana-Regular.ttf
    - family: LibertinusMono_Regular
      fonts:
        - asset: assets/fonts/Libertinus_Mono/LibertinusMono-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
