// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB17Pn7uiOyhgXZBmD579V_86o45dSHino',
    appId: '1:840636845965:web:38e88e8a0aedb437f0b7c4',
    messagingSenderId: '840636845965',
    projectId: 'ecommerce-project-55b3c',
    authDomain: 'ecommerce-project-55b3c.firebaseapp.com',
    storageBucket: 'ecommerce-project-55b3c.firebasestorage.app',
    measurementId: 'G-GFTN2YJJ0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCkC_091t7Itl9lLqZzC-mQIhUBP2b838',
    appId: '1:840636845965:android:05a7650bd98eee59f0b7c4',
    messagingSenderId: '840636845965',
    projectId: 'ecommerce-project-55b3c',
    storageBucket: 'ecommerce-project-55b3c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB17Pn7uiOyhgXZBmD579V_86o45dSHino',
    appId: '1:840636845965:web:f588bdf207c5568af0b7c4',
    messagingSenderId: '840636845965',
    projectId: 'ecommerce-project-55b3c',
    authDomain: 'ecommerce-project-55b3c.firebaseapp.com',
    storageBucket: 'ecommerce-project-55b3c.firebasestorage.app',
    measurementId: 'G-MG70NK1MKP',
  );
}
